apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: suricata

resources:
  - suricata-namespace.yaml
  - suricata-deployment.yaml
  - suricata-service.yaml

configMapGenerator:
  - name: suricata
    files:
      - suricata.yaml