apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zeek

resources:
  - zeek-namespace.yaml
  - zeek-deployment.yaml
  - zeek-service.yaml

configMapGenerator:
  - name: zeek
    files:
      - zeek.yaml