apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeek
  namespace: zeek
  labels:
    app: zeek
spec:
  selector:
    matchLabels:
      app: zeek
  template:
    metadata:
      labels:
        app: zeek
    spec:
      hostNetwork: true
      containers:
        - name: zeek
          image: zeek/zeek:latest
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          volumeMounts:
            - name: zeek-logs
              mountPath: /var/log/zeek
            - name: zeek-config
              mountPath: /usr/local/zeek/etc
          ports:
            - containerPort: 4777
          env:
            - name: ZEEK_INTERFACE
              value: "eth0"
      volumes:
        - name: zeek-logs
          emptyDir: {}
        - name: zeek-config
          configMap:
            name: zeek-config