apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: suricata
  name: suricata
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: suricata
  template:
    metadata:
      labels:
        app.kubernetes.io/name: suricata
    spec:
      hostNetwork: true
      containers:
        - name: suricata
          image: jasonish/suricata:latest
          command:
            - /usr/bin/suricata
          args:
            - -i
            - eth0
            - -v
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          resources:
            limits:
              memory: 10Gi
              cpu: 500m
            requests:
              memory: 10Gi
              cpu: 500m
          volumeMounts:
            - name: suricata-config
              mountPath: /etc/suricata/suricata.yaml
              subPath: suricata.yaml
            - name: suricata-logs
              mountPath: /var/log/suricata
      volumes:
        - name: suricata-config
          configMap:
            name: suricata
        - name: suricata-logs
          emptyDir: {}
